---
before_deploy:
  - "zip -r freelec-springboot2-webservice *"
  - "mkdir -p deploy"
  - "mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip"
before_install:
  - "chmod +x gradlew"
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
deploy:
  -
    access_key_id: $AWS_ACCESS_KEY
    acl: private
    bucket: freelec-springboot-build-test
    local_dir: deploy
    provider: s3
    region: ap-northeast-2
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true
    wait-until-deployed: true
jdk:
  - openjdk11
language: java
notifications:
  email:
    recipients:
      - emotional2u@naver.com
script: "./gradlew clean build"
